# Generated by Django 5.2.1 on 2025-05-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studiengang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abschluss', models.CharField(max_length=50)),
                ('form', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Studiengänge',
            },
        ),
    ]
