# Generated by Django 5.2.1 on 2025-05-12 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bewerbung', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studiengang',
            options={},
        ),
        migrations.AlterField(
            model_name='studiengang',
            name='form',
            field=models.CharField(choices=[('Online', 'Online'), ('Präsenz', 'Präsenz')], default='Online', max_length=10),
        ),
        migrations.CreateModel(
            name='Bewerbung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('abschlus', models.CharField(max_length=100)),
                ('sprachen', models.CharField(max_length=100)),
                ('kommentar', models.TextField(blank=True, null=True)),
                ('studiengang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bewerbung.studiengang')),
            ],
            options={
                'verbose_name_plural': 'Studiengänge',
            },
        ),
    ]
