# Generated by Django 5.2.1 on 2025-05-12 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bewerbung', '0002_alter_studiengang_options_alter_studiengang_form_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studiengang',
            options={'verbose_name_plural': 'Studiengänge'},
        ),
        migrations.DeleteModel(
            name='Bewerbung',
        ),
    ]
