# Generated by Django 5.2.1 on 2025-05-12 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bewerbung', '0003_alter_studiengang_options_delete_bewerbung'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bewerbung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('abschlus', models.CharField(max_length=100)),
                ('sprachen', models.CharField(max_length=100)),
                ('kommentar', models.TextField(blank=True, null=True)),
                ('studiengang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bewerbung.studiengang')),
            ],
        ),
    ]
