# Generated by Django 5.2.1 on 2025-05-12 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bewerbung', '0004_bewerbung'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bewerbung',
            options={'verbose_name_plural': 'Bewerbungen'},
        ),
    ]
