# Generated by Django 5.2.1 on 2025-05-12 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bewerbung', '0005_alter_bewerbung_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kontaktanfrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('nachricht', models.TextField()),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='bewerbung',
            old_name='abschlus',
            new_name='abschluss',
        ),
        migrations.AddField(
            model_name='bewerbung',
            name='status',
            field=models.CharField(choices=[('in_bearbeitung', 'In Bearbeitung'), ('genehmigt', 'Genehmigt'), ('abgelehnt', 'Abgelehnt')], default='in_bearbeitung', max_length=20),
        ),
        migrations.AddField(
            model_name='bewerbung',
            name='zeugnis',
            field=models.FileField(blank=True, null=True, upload_to='zeugnisse/'),
        ),
        migrations.CreateModel(
            name='Zugangsvoraussetzung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abschluss', models.CharField(max_length=100)),
                ('sprachen', models.CharField(max_length=100)),
                ('studiengang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bewerbung.studiengang')),
            ],
            options={
                'verbose_name_plural': 'Zugangsvoraussetzungen',
            },
        ),
    ]
