# Generated by Django 5.2.1 on 2025-05-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bewerbung', '0006_kontaktanfrage_rename_abschlus_bewerbung_abschluss_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bewerbung',
            name='name',
        ),
        migrations.AddField(
            model_name='bewerbung',
            name='nachname',
            field=models.CharField(default='Nicht angegeben', max_length=100),
        ),
        migrations.AddField(
            model_name='bewerbung',
            name='vorname',
            field=models.CharField(default='Nicht angegeben', max_length=100),
        ),
    ]
