# Generated by Django 5.2.1 on 2025-05-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bewerbung', '0007_remove_bewerbung_name_bewerbung_nachname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bewerbung',
            name='nachname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bewerbung',
            name='vorname',
            field=models.CharField(max_length=100),
        ),
    ]
