# Generated by Django 5.2.1 on 2025-05-12 13:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bewerbung', '0008_alter_bewerbung_nachname_alter_bewerbung_vorname'),
    ]

    operations = [
        migrations.AddField(
            model_name='bewerbung',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bewerbung',
            name='geburtsdatum',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bewerbung',
            name='telefon',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
