# Generated by Django 5.2.1 on 2025-05-12 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bewerbung', '0009_bewerbung_adresse_bewerbung_geburtsdatum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bewerbung',
            name='zeugnis',
            field=models.FileField(null=True, upload_to='zeugnisse/'),
        ),
        migrations.CreateModel(
            name='BewerbungsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_alt', models.CharField(max_length=20)),
                ('status_neu', models.CharField(max_length=20)),
                ('geändert_am', models.DateTimeField(auto_now_add=True)),
                ('bewerbung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bewerbung.bewerbung')),
            ],
        ),
    ]
