# Generated by Django 5.2.1 on 2025-05-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bewerbung', '0010_alter_bewerbung_zeugnis_bewerbungslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='bewerbung',
            name='einwilligung',
            field=models.BooleanField(default=False, help_text='Ich bin mit der Verarbeitung meiner Daten gemäß Datenschutzerklärung einverstanden.'),
        ),
        migrations.AddField(
            model_name='bewerbung',
            name='status_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
