# Generated by Django 5.2.1 on 2025-06-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bewerbung', '0011_bewerbung_einwilligung_bewerbung_status_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontaktanfrage',
            name='vorname',
            field=models.CharField(default='Unbekannt', max_length=100),
        ),
    ]
