# Generated by Django 5.2.1 on 2025-06-16 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bewerbung', '0012_kontaktanfrage_vorname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abschluss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Abschlüsse',
            },
        ),
        migrations.AlterField(
            model_name='bewerbung',
            name='abschluss',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bewerbung.abschluss'),
        ),
    ]
