# Generated by Django 5.2.1 on 2025-06-16 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bewerbung', '0013_abschluss_alter_bewerbung_abschluss'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kontaktanfrage',
            options={'verbose_name_plural': 'Kontaktanfragen'},
        ),
    ]
