# Generated by Django 5.2.3 on 2025-06-18 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bewerbung', '0014_alter_kontaktanfrage_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bewerbungslog',
            old_name='geändert_am',
            new_name='geaendert_am',
        ),
    ]
